obj-$(CONFIG_LGE_DISPLAY_JOAN_COMMON) += joan/
obj-$(CONFIG_LGE_DISPLAY_LUCY_COMMON) += lucy/


obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_dsi.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_dsi_panel.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_fb.o
obj-$(CONFIG_LGE_DISPLAY_CONTROL) += lge_display_control.o
obj-$(CONFIG_LGE_DISPLAY_AMBIENT_SUPPORTED) += lge_mdss_ambient.o
obj-$(CONFIG_LGE_DISPLAY_COMFORT_MODE) += lge_comfort_view.o
obj-$(CONFIG_LGE_DISPLAY_COLOR_MANAGER) += lge_color_manager.o
obj-$(CONFIG_LGE_DISPLAY_ERROR_DETECT) += lge_error_detect.o
obj-$(CONFIG_LGE_INTERVAL_MONITOR) += lge_interval_monitor.o
obj-$(CONFIG_LGE_FBCN) += lge_fbcn.o
