obj-y += lge_mdss_dsi_joan.o
obj-y += lge_mdss_dsi_panel_joan.o
obj-$(CONFIG_LGE_DISPLAY_CONTROL) += lge_display_control_joan.o
obj-$(CONFIG_LGE_DISPLAY_ERROR_DETECT) += lge_error_detect_joan.o
obj-$(CONFIG_LGE_DISPLAY_AMBIENT_SUPPORTED) += lge_mdss_ambient_joan.o
obj-$(CONFIG_LGE_DISPLAY_INTERNAL_TEST) += lge_internal_test.o
